name: Webhost
main: me.kyllian.webhost.WebhostPluginSpigot
version: ${project.version}
author: Kyllian
api-version: 1.13

commands:
  webhost:
    usage: /<command>
    description: Base command of the plugin